### ISSUE TITLE
Audio/local/path and Audio/meta/guid not using folder number prefixes

### ISSUE THREAD

**Issue by agentirons** [jgonyea/grav-plugin-podcast#39]
After updating to v3.0, I found that the format of the image and audio tags had changed slightly and prevented me from loading the page editor until I removed or modified the image tag (separate issue). After I fix this and open the editor, if I select the .mp3 media from the dropdown on the Podcast Audio tab, the Audio:local:path: field and the Audio:meta:guid field do not use the folder number prefixes of my site, and are missing the "user/pages/" beginning, resulting in a broken link to the audio.

As you can see in this example from a podcast-episode.md file, the first instance of the path is correct but the other two fields are not.

```
    audio:
        local:
            select: Episode8_InvasionOfTheBodySnatchers.mp3
            user/pages/01.the-305/08.invasion-of-the-body-snatchers/Episode8_InvasionOfTheBodySnatchers.mp3:
                name: Episode8_InvasionOfTheBodySnatchers.mp3
                type: audio/mpeg
                size: 55239391
                path: /the-305/invasion-of-the-body-snatchers/Episode8_InvasionOfTheBodySnatchers.mp3
        meta:
            guid: /the-305/invasion-of-the-body-snatchers/Episode8_InvasionOfTheBodySnatchers.mp3
            type: audio/mpeg
            duration: '57:32'
            enclosure_length: 55239391
```

**Comment by jgonyea** [comment]
I have the following structure:

```
root (/grav-dev)
|- podcast-channel.md (04.technology-today)
  |- podcast-series.md (01.series-1)
    |- podcast-episode.md (01.episode-1)
    |- podcast-episode.md (02.episode-2)
```
I do see the lack of the numbered routes:
```
    audio:
        local:
            select: 'Pigstep Minecraft Remix.mp3'
            'user/pages/04.technology-today/01.series-1/02.episode-2/Pigstep Minecraft Remix.mp3':
                name: 'Pigstep Minecraft Remix.mp3'
                type: audio/mpeg
                size: 5057025
                path: '/grav-dev/technology-today/series-1/episode-2/Pigstep Minecraft Remix.mp3'
        meta:
            guid: '/grav-dev/technology-today/series-1/episode-2/Pigstep Minecraft Remix.mp3'
            type: audio/mpeg
            duration: '3:31'
            enclosure_length: 5057025
```
But I'm still able to route the files just fine on the front-end.  Can you clear your cache and try viewing again?

![image](https://user-images.githubusercontent.com/1057441/105929476-aee8bc80-6015-11eb-8145-1a7107b3db65.png)

**Comment by jgonyea** [comment]
I just also realized that images also broke.

It has to do with the breaking changes of the image field I had to make to get around the Grav 1.6 file field -> Grav 1.7 filepicker field issue.

To manually fix, open each page that has an image. If you're doing this locally, it probably will be faster to open the *.md files in a text editor.

You'll see something along the lines like:
```
series:
    image:
        user/pages/01.channel/01.series/featured_image.jpg:
            name: featured_image.jpg
            type: image/jpeg
            size: 8206
            path: user/pages/01.channel/01series/featured_image.jpg
```

This needs to be changed to:

```
series:
    image: featured_image.jpg
```
